language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: Zke+cGe+yggHXoKNhR/VHDhylUumi8Hzx/y/JsPlz269ezU40hHue1xNXtJoXK9tTyoJdx54L5e+c8HgNTyDFu3/qxb4wFHll5ug5jFEYrz8WkVPvN7XOMcQrkKcVzXdoa8D2EJ82zJGURoJc1SVhxDuMphzMiOPMjzU/oslnt4=
    - secure: KeYL2O8nv1MIqZ1RWn/u2puENikXjWyBg9pyG1aLRYpefBMmx3w6P1WcIXlF06dyzeUgMSCHqZAk+m+OxGCOKzqNZm/P0bBnxWlHKCME02q4g+7bQZ6jlqQM65KUJ1nSCLB0D8Iv17acaBU10h6L2qgJ1GybgvbkDWC0rhAVFVo=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.db.gbu import get_config; print(get_config())'
- ./bin/bob_dbmanage.py gbu download
- ./bin/coverage run --source=bob.db.gbu ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
